development:
  secret_key_base: 304ede5310bc3a184f4c746fc8138c36e0f8c340866d4a49a3ef658bd68bffa4e9e847ca27a645d2b5491a4569cab958bff0a7ec707504c7cff1f10e9f2d7035
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>

test:
  secret_key_base: 7d92dbd2fe5f5213dd5bc9a8de3a9cbe2d18d20d54665af6727251b5bfb9f2e7af1122d5f6e9e0b7af7f3c6fec508cd3fce069bad570f4bacda19d86e0d4b1db
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
