# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 087bb420724dd5bb83b38fe3ce3aabdddbed3cc71ad5dfaedb0cf3d70d38fa4dd8eb113f528f4d002f09842111fc46c6f70fca0ade03f3eeb31d85c7182d71c0

test:
  secret_key_base: 76034c21da5eb2c16883f628e7e42d4cc44a4627c04dea940ac80fee2bb090c70c35e25a098dc691080cd21de2dd710e275f77d648ddbf33b6b883e032fc9b58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
